### ISSUE TITLE
Time information on trajectories

### ISSUE THREAD

**Issue by ruminahui** [dongfang-steven-yang/vci-dataset-citr#1]
Hi,

I was wondering if there was any timing information associated with the trajectory points.

Currently, the only available information I can see is the frame number associated with a particular point. However, I would like to express this in relative time values. 

According to the specs of the DJI Phantom3 drone specs, at the resolution mentioned in this repo(FHD: 1920x1080p) the camera can capture at different rates (24/25/30 fps). Would you be able to confirm what frame rate was used for capturing the clips, or any relevant information to extract the relative timing information associated with points in a particular trajectory?

Thanks for the help

**Comment by dongfang-steven-yang** [comment]
Hi, 

Thanks for the interest in our dataset. The FPS associated with the frames in CITR is 29.97. (Note that in the other dataset DUT the FPS is 23.98). You may find more detail information in our [paper](https://arxiv.org/abs/1902.00487). 

Thanks,
DF

**Comment by ruminahui** [comment]
Thanks for the help!
