### ISSUE TITLE
Hi Yang, Do you have some dataset to test the IPM measuring method。

### ISSUE THREAD

**Issue by AdamPengG** [dongfang-steven-yang/vci-dataset-citr#2]
Hi Yang, I wanna to test the precision of Inverse Perspective Mapping . Do you have the dataset which include the camera's the Fov ,the relation between the world coordinate (X, Y, Z) and image coordinate (X, Y, Z) , focal length, the camera's height, the camera's patch angle, its Intrinsic matrix and the picture the camera taking. 
Hope to hear from you soon， I will appreacite it .
杨同学您好，我在您的git上看见了IPM算法的过程，我想验证一下这个算法的精度。您可以分享一下您测量IPM算法的数据集吗，包括相机参数和能做测量的图片。

**Comment by dongfang-steven-yang** [comment]
Hi, I don't quite understand your question. This work applies the RANSAC to calculate the perspective mapping. This is to achieve the video stabilization as described in the paper.

**Comment by AdamPengG** [comment]
Thank you Yang. I mistakenly put my question in vci program. I saw your social-distancing-monitoring which uses the IPM measuring method to detect the social distances between the people. Is it?

**Comment by dongfang-steven-yang** [comment]
In social distancing monitoring, the last two datasets use the OpenCV package to calculate the transformation matrix. However, the first dataset, i.e., the oxford dataset, provides the camera calibration info. This might be helpful for your purpose.
